(defun main ()
  (dotimes (_ (read))
    (let ((input (make-array (read) :element-type 'fixnum))
          (sum 0)
          (offset))
      (do ((i 0 (1+ i)))
          ((>= i (length input)))
          (incf sum (setf (aref input i) (read))))
      (setf offset (/ sum (1+ (length input))))
      (dotimes (i (length input))
        (format t "~A "(- (aref input i) offset))))
    (terpri)))

(main)
