(defun is-good (str)
  (do ((i 0 (1+ i))
       (buf (make-string 3)))
      ((>= i (length str)) nil)
      (if (>= 2 i)
          (setf (char buf i) (char str i))
          (setf (char buf 0) (char buf 1)
                (char buf 1) (char buf 2)
                (char buf 2) (char str i)))
      (when (or (string= buf "010") (string= buf "101"))
        (return t))))

(defun main ()
  (dotimes (_ (read))
    (if (is-good (read-line))
        (write-string "Good")
        (write-string "Bad"))
    (terpri)))

(main)
