(defun main ()
  (dotimes (_ (read))
    (do ((minval 1000000000000)
         (maxval 0)
         (arr (make-array (read) :element-type 'fixnum))
         (k (read))
         (i 0 (1+ i)))
        ((>= i (length arr)) (if (or (= 1 (length arr)) 
                                     (<= (+ minval maxval) k))
                                 (write-string "YES")
                                 (write-string "NO")))

        (let ((a (read)))
          (setf (aref arr i) a)
          (when (> a maxval)
            (setf maxval a))
          (when (< a minval)
            (setf minval a))))
    (terpri)))

(main)
